# Copyright 2010 - 2011, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# Make private headers available
env.Append(CPPPATH=[env.Dir('../../daemon').srcnode()])

# Make WDK headers available
# TODO: Fix this to use WIN7BASE instead of C:/WinDDK/7600.16385.1
env.AppendUnique(CPPPATH=['C:/WinDDK/7600.16385.1/inc/ddk'])

# Make WDK libraries available
# TODO: Fix this to use WIN7BASE instead of C:/WinDDK/7600.16385.1
if env['CPU'] == 'IA64':
    env.AppendUnique(LIBPATH=['C:/WinDDK/7600.16385.1/lib/win7/amd64'])
elif env['CPU'] == 'x86':
    env.AppendUnique(LIBPATH=['C:/WinDDK/7600.16385.1/lib/win7/i386'])
else:
    # Houston, we have a problem.
    pass

env.AppendUnique(LIBS=['fltLib.lib', 'Bthprops.lib'])

# Build using Windows
srcs = env.Glob('*.cc')
Return('srcs')
