# Copyright 2011, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# Install source
if env['OS'] == 'android':
    distDir = '$DISTDIR/alljoyn_android/alljoyn'
    env.Install(distDir, env.Glob('alljoyn/AndroidManifest.xml'))
    env.Install(distDir, env.Glob('alljoyn/.classpath'))
    env.Install(distDir, env.Glob('alljoyn/.project'))
    env.Install(distDir, Dir('alljoyn/.settings').srcnode())
    env.Install(distDir, env.Glob('alljoyn/default.properties'))
    env.Install(distDir, Dir('alljoyn/jni').srcnode())
    env.Install(distDir, Dir('alljoyn/src').srcnode())
    env.Install(distDir, Dir('alljoyn/res').srcnode())

    distDir = '$DISTDIR/alljoyn_android/bundle'
    env.Install(distDir, env.Glob('bundle/AndroidManifest.xml'))
    env.Install(distDir, env.Glob('bundle/.classpath'))
    env.Install(distDir, env.Glob('bundle/.project'))
    env.Install(distDir, env.Glob('bundle/default.properties'))
    env.Install(distDir, Dir('bundle/src').srcnode())
